### ISSUE TITLE
coordinates out of range

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#10]
I am facing an issue with lon la out of range in mcera5, my understanding is era5 is global so wonder why I am having this error below:

extracting weather data locally from c:/Users/sarr/Documents/Spatial_Data/era5 
Input coordinates match ERA5 grid, no distance weighting required.
 Error in nc_to_df(nc, long, lat, start_time, end_time, dtr_cor = dtr_cor,  : 
  Requested coordinates are not represented in the ERA5 netCDF (both longitude and latitude out of range). 

my coordinates setting are:

xmn <- -18
  xmx <- -12
  ymn <- 12
  ymx <- 17
  

Any hint of solving this?

**Comment by fipoucat** [comment]
maybe not thez right place to post this kind of issue?

**Comment by dklinges9** [comment]
Hi @fipoucat , apologies that no one addressed this issue from a while back. You provided this issue when a lot of things were still in flux with package development, so I imagine your query may work now. I'm closing this for housekeeping purposes but please feel free to reach out (including by submitting a new issue) with other questions!

Best, Dave
