### ISSUE TITLE
Client has not agreed to the required terms and conditions

### ISSUE THREAD

**Issue by zhengjiji456** [dklinges9/mcera5#16]
Hi,
I followed the instruction but met a problem.

> request_era5(request = req, uid = uid, out_path = "/lustre/home/R/microclimate")
Your request will all be queried at once and does not need to be combined.
Requesting data to the cds service with username xxxxxxx
Error: Client has not agreed to the required terms and conditions.http://copernicus-climate.eu/exc/missing-termsClient has not agreed to the required terms and conditions.list(required_terms = list(list(title = "Licence to use Copernicus Products", url = "https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products", reason = "missing")))FALSEclient

**Comment by dklinges9** [comment]
Hi,

By the look of it, it appears that you did not yet agree to the Terms and Conditions set by the Copernicus Climate Data Store. You can do so by clicking the following link (while logged in):
https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products  

You can follow the step-by-step instructions of how to get started with mcera5 by trying the vignette, which is [here on github](https://github.com/dklinges9/mcera5/blob/master/vignettes/mcera5_vignette.Rmd). Please let me know if you have further trouble, or whether we can close this issue!

**Comment by zhengjiji456** [comment]
Thanks for your quick response. The problem has been solved.
