### ISSUE TITLE
Rainfall returned by extract_precip in m rather than mm

### ISSUE THREAD

**Issue by ilyamaclean** [dklinges9/mcera5#20]
Vignette states that the vector created by `extract_precip` is ready to be used as an input to the `runauto` function from the `microclima` package. However returned values are in m, but runauto expects values in mm

**Comment by dklinges9** [comment]
Thanks for that catch. precip was returned in mm if `convert_daily` left as TRUE per default, but conversion from m to mm needed when `convert_daily` was FALSE and hourly values were returned. Now fixed in 55db3f37c268f19ecd372b5ae65cfaf01b2998c9.
