### ISSUE TITLE
 extract_clim() returns `in hyper_filter.tidync(., longitude = longitude == long, latitude = latitude ==  :    subexpression for [longitude] results in empty slice`

### ISSUE THREAD

**Issue by Paul-Haimerl** [dklinges9/mcera5#26]
Hi guys,
when trying to extract a 2m surface temperature time series for a specific location, extract_clim() returns the Error:
`in hyper_filter.tidync(., longitude = longitude == long, latitude = latitude ==  :    subexpression for [longitude] results in empty slice`
I have made sure that the specific location is within the long/lat scope of the .nc file. Optional arguments of extract_clim() are left at their defaults.

Can you please point me towards a fix?

Many thanks

**Comment by dklinges9** [comment]
Hi Paul, could your send me your code for how you queried the era5 data request and how you parameterized extract_clim()? I'll take a look. Depending on the size of your netcdf you may also be able to attach it here (or send to dklinges9@gmail.com)

**Comment by Paul-Haimerl** [comment]
Ah sorry, I was not aware you had to download more than just the 2m temperature series (I went through the Copernicus data store, not the API). Many thanks nonetheless.

**Comment by dklinges9** [comment]
No worries. Although I do encourage querying via the API and the mcera5`build_era5_request` and `request_era5` functions, it's on my list to provide functionality in the package for ERA5 data that was downloaded otherwise. Good to know of users of this approach.
