### ISSUE TITLE
rgdal

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#28]
is there any plan to avoid or suppress rgdal when installing this pqckage mcera5

**Comment by dklinges9** [comment]
Hi, as of 27 Feb mcera5 should not be dependent on rgdal, which was removed by no longer relying on the intermediary microclima as of the most recent commit. However, [at least one user has found a bug](https://github.com/dklinges9/mcera5/issues/27) with this new version, which I will be addressing soon.

Have you installed the most recent version of mcera5, and if so are you facing a particular problem related to rgdal? Thanks for any details you can provide. Best, Dave

**Comment by fipoucat** [comment]
I just reinstalled now and it is working now.

Thank you

**Comment by dklinges9** [comment]
Hi, great. If you face any issues with the new version please do submit a new issue. Cheers, Dave
