### ISSUE TITLE
intergrate ability to download new 1950-1979 dataset

### ISSUE THREAD

**Issue by everydayduffy** [dklinges9/mcera5#3]
Code needs to be added to check input date range:

If split across 1978/1979 boundary then return with error saying split requests.
If whole date range is pre 1979 then something like this needs to be added - `req[[1]]$dataset_short_name <- "reanalysis-era5-single-levels-preliminary-back-extension"` during building of a request.

**Comment by dklinges9** [comment]
Given that ERA5 re-analysis has been updated to included the preliminary after 1959, no changes need to be made at this point for data 1959 - present. Years 1950 - 1959 would still be need a separate request structure, so keeping this open for now.

**Comment by dklinges9** [comment]
1950 - 1959 no longer needs a separate request either, so closing.
