### ISSUE TITLE
netlong and downlong erroneous multiplication by 0.0036

### ISSUE THREAD

**Issue by ilyamaclean** [dklinges9/mcera5#34]
in extract_clima and extract_clim (via nc_to_df) you should change:

netlong = abs(msnlwrf) * 0.0036
downlong = msdwlwrf * 0.0036

to 

netlong = abs(msnlwrf) 
downlong = msdwlwrf

The units of longwave radiation in the nc file are already W m**-2 and not J m**-2 so no need to multiply by  0.0036

**Comment by dklinges9** [comment]
It seems that this multiplication has been there for years, can be traced back to the origin of the package (before I began helping developing), [see here from 4 years ago](https://github.com/dklinges9/mcera5/blob/dd9b92525aed73bca1578f501baa4f391586f875/R/functions.R#L106). I faintly recall scratching my head at why this multiplication was occurring when looking through the code in ~2021, as indeed the ERA5 variables are [already in W m-2](https://cds-beta.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=overview)....

the derivative variables netlong, downlong, uplong were primarily for providing to microclima functions. Even though microclima is largely deprecated now, I just want to confirm that to your knowledge making this change won't result in any backwards compatibility issues? If not then I'll go ahead.

**Comment by ilyamaclean** [comment]
Ah yes that's right - for microclima radiation is in MJ/m^2 and all variables were converted to that hence why W/m^2 longwave was multipled by 0.0036. However for the microclimf and micropoint option outputs you need to convert radiation back to W/m^2 so you need  to divide by 0.0036 to convert back from MJ/m^2 to W/M^2 (you've already done this for your shortwave outputs). 

I did a pull request and fixed it, but I think the commits went out of sync as you were also commiting at the same time so probably easiest to fix manually. If you want to cross reference anything though - just check the verison here  https://github.com/ilyamaclean/mcera5.

**Comment by dklinges9** [comment]
This issue has now been addressed in the recent [merge](https://github.com/dklinges9/mcera5/commit/8205e5d06c68bdbe9a4248a682b65eb72f94c57b) so as to have compatibility with different microclimate R packages (e.g. microclima vs micropoint)
