### ISSUE TITLE
Bug in direct radiation calculus in micropoint data preparation

### ISSUE THREAD

**Issue by martin-macek** [dklinges9/mcera5#43]
Wrong unit conversion for direct radiation calculation (raddr) for "micropoint" format. Should be raddr = (rad_dni * si)/0.0036 like for difrad.

dplyr::mutate(raddr = (rad_dni * si)/3600,
                    difrad = rad_dif/0.0036,
                    swdown = raddr + difrad,
                    pres = pressure/1000, # convert to kPa,
                    difrad = rad_dif/0.0036,
                    precip = precip,
                    lwdown = downlong/0.0036) %>%

https://github.com/dklinges9/mcera5/blob/43c0b2d07ff9fec47f1d5bc9e0b165597a788280/R/internal.R#L251

**Comment by dklinges9** [comment]
Yep, good catch! This was from a recent patch and so hasn't been around too long, luckily. Fixed with the [most recent commit](https://github.com/dklinges9/mcera5/commit/c3b884ef4143e8e4cfda393fa96afb51b99b029a)
