### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#5]
I am installing the package from github on window but getting error message: failed to install package mcera5 from github.

Is there any binary or on cran?

Thanks

**Comment by everydayduffy** [comment]
> Is there any binary or on cran?

No there isn't. If you share some details of where it's failing I might actually be able to help. Installs fine on my Windows machine...

**Comment by fipoucat** [comment]
Thank you, fixed now.

It was related to digest installation.
