### ISSUE TITLE
download related error

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#6]
Have an error and can't figure why from below code:

>library(lubridate)
>library(microclima)
>library(mcera5)
 >xmn <- -18
>  xmx <- -12
 > ymn <- 12
>  ymx <- 17
 
 
 > # temporal extent
 > st_time <- lubridate::ymd("2019:01:01")
 > en_time <- lubridate::ymd("2019:12:31")
 
 > # filename and location for downloaded .nc files
>  file_prefix <- "era5"
>op <- "C:/Users/sarr/Documents/Spatial_Data/"
 
 
>  # build a request (covering multiple years)
>  req <- build_era5_request(xmin = xmn, xmax = xmx,
 >                           ymin = ymn, ymax = ymx,
   >                         start_time = st_time,
   >                         end_time = en_time,
  >                          outfile_name = file_prefix)
  Error in .uni_dates(start_time, end_time) :
  could not find function ".uni_dates"

Thanks for any hint?

**Comment by everydayduffy** [comment]
Hello,

Thanks for the details. Should be fixed now.
