### ISSUE TITLE
request error

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#7]
Hi James,
A follow up problem related to my former post you solved. At the request step I am getting an error and hope support onit.

Sorry Mike, I am getting another error message, is-it also mcera5 related?

 > request_era5(request = req, uid = "XXXX", out_path = op)
Error: Data identifier reanalysis-era5-single-levels is not found in Web API, CDS or ADS datasets.
                 Or your login credentials do not match your request.

XXXX is my 4 digit of key in quote.

Thanks

**Comment by everydayduffy** [comment]
Hi,

As before, not much I can do without a reproducible example/some more details. Which year(s) are you requesting data for?

**Comment by fipoucat** [comment]
Script beloq:

> library(mcera5)
> library(microclima)
>   xmn <- -18
>   xmx <- -12
>   ymn <- 12
>   ymx <- 17
>   
>   
>   # temporal extent
>   st_time <- lubridate::ymd("2019:01:01")
>   en_time <- lubridate::ymd("2019:12:31")
>   
>   # filename and location for downloaded .nc files
>   file_prefix <- "era5"
>   op <- "C:/Users/sarr/Documents/Spatial_Data/"
>   
>   
>   # build a request (covering multiple years)
>   req <- build_era5_request(xmin = xmn, xmax = xmx,
+                             ymin = ymn, ymax = ymx,
+                             start_time = st_time,
+                             end_time = en_time,
+                             outfile_name = file_prefix)
>   
>   # Obtaining data with a request
>   request_era5(request = req, uid = "XXXX", out_path = op)
Error: Data identifier reanalysis-era5-single-levels is not found in Web API, CDS or ADS datasets.
                 Or your login credentials do not match your request.

**Comment by everydayduffy** [comment]
That request works fine with my credentials, so something is likely wrong with your UID/API Key. 

Your UID should be 5 digits long, I noticed you have used 4 Xs to represent yours in your example. Make sure this is right.

**Comment by fipoucat** [comment]
It looks that it can be 4 or 5 (some users have 4 others 5) fro what I have
seen on
https://cds.climate.copernicus.eu/live/queue

**Comment by everydayduffy** [comment]
Ah good point. Have you double checked your API Key/UID, and made sure you have run 

`ecmwfr::wf_set_key(user = uid,
                   key = cds_api_key,
                   service = "cds")`

as shown in the vignette?

**Comment by fipoucat** [comment]
Ok, that was  causing the problem.

Thank you once again

**Comment by fipoucat** [comment]
Hi James,

I am back again with another error message in the script I am trying to run?


> micro<-micro_era5(loc = c(-17.35, 14.60), dstart = "02/10/2019" ,
+ dfinish = "03/10/2019", spatial = '/home/sarr/work/Spatial_Data/era5')
If program is crashing, try run.gads = 2.

downloading DEM via package elevatr
Downloading DEMs [===========================] 100% eta: 0s
Mosaicing & Projecting
Note: Elevation units are in meters.
Note: The coordinate reference system is:
+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
extracting weather data locally from /home/sarr/work/Spatial_Data/era5
Error in mcera5::point_nc_to_df(nc = paste0(spatial, "_", years, ".nc"), :
unused arguments (x = loc[1], y = loc[2])
and more : Warning message:
In sp::proj4string(locations) :
CRS object has comment, which is lost in output


Best regards,

**Comment by fipoucat** [comment]
>   xmn <- -18
>   xmx <- -12
>   ymn <- 12
>   ymx <- 17
>   
>   
>   # temporal extent
>   st_time <- lubridate::ymd("2019:01:01")
>   en_time <- lubridate::ymd("2019:12:31")
>   
>   # filename and location for downloaded .nc files
>   file_prefix <- "era5"
>   op <- "C:/Users/sarr/Documents/Spatial_Data/"
>   
>   
>   # build a request (covering multiple years)
>   req <- build_era5_request(xmin = xmn, xmax = xmx,
+                             ymin = ymn, ymax = ymx,
+                             start_time = st_time,
+                             end_time = en_time,
+                             outfile_name = file_prefix)
>   
>   # Obtaining data with a request
>   request_era5(request = req, uid = "XXXX", out_path = op)
Error: Data identifier reanalysis-era5-single-levels is not found in Web API, CDS or ADS datasets.
                 Or your login credentials do not match your request.
