### ISSUE TITLE
point_nc_to_df related error

### ISSUE THREAD

**Issue by fipoucat** [dklinges9/mcera5#8]
Hi James,

I am back again with another error message in the script I am trying to run?
 micro<-micro_era5(loc = c(-17.35, 14.60), dstart = "02/10/2019" ,
+ dfinish = "03/10/2019", spatial = '/home/sarr/work/Spatial_Data/era5')
If program is crashing, try run.gads = 2.

downloading DEM via package elevatr
Downloading DEMs [===========================] 100% eta: 0s
Mosaicing & Projecting
Note: Elevation units are in meters.
Note: The coordinate reference system is:
+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
extracting weather data locally from /home/sarr/work/Spatial_Data/era5
Error in mcera5::point_nc_to_df(nc = paste0(spatial, "_", years, ".nc"), :
unused arguments (x = loc[1], y = loc[2])
and more : Warning message:
In sp::proj4string(locations) :
CRS object has comment, which is lost in output

Best regards,

**Comment by everydayduffy** [comment]
Thanks for highlighting this. It seems to be an issue with the code in NicheMapR. I recently changed the names of inputs to the functions, which has caused micro_era5 to break. I have raised an issue (https://github.com/mrke/NicheMapR/issues/12#issue-778117583) on the repo. 

Cheers

James
